# config.yaml
general:
  domain: -10,29,40,47.5
  domainName: 'MED2'
  crs: 3035
  use_sedoo_drive: False 
  root_data: /data/shared/
hs:
  dir_data: ORIGIN/hotspots2025
  sats: ['']
event:
  dir_data: ORIGIN/MED2_fire_events 
  dir_geoJson: ORIGIN/MED2_fire_events/GeoJson
  dir_frp: ORIGIN/MED2_fire_events/FRP
  dir_cloudMask: ORIGIN/RASTER/cloudMask/
  start_time: '2025-01-01_0000'
  end_time_hard: '2025-12-31_2350'
  mask_HS: /data/shared/HSDensity_VIIRS2025/data_mask_buffer_3857.geojson
  eurostat: 'EUROSTAT/COMM_RG_01M_2016_3035.gpkg'
  cloudMask_mtg: "FCI/RASTER/cloudMask/"
  dir_hs_log: "ORIGIN/MED2_fire_events/HS_log/"
postproc:
  dir_FWI:  AROME/FWI
  dir_WIND: AROME/FORECAST/WIND/

