# config.yaml
general:
  domain: -10,35,20,52
  domainName: 'SILEX'
  crs: 25829
hs:
  dir_data: /mnt/dataEstrella2/SILEX/VIIRS-HotSpot
  sats: ['VIIRS_NOAA20_NRT', 'VIIRS_NOAA21_NRT', 'VIIRS_SNPP_NRT']
event:
  dir_data: /mnt/dataEstrella2/SILEX/VIIRS-HotSpot/FireEvents
  dir_geoJson: /mnt/dataEstrella2/SILEX/VIIRS-HotSpot/FireEvents/GeoJson
  start_time: '2025-05-18_0000'
