# config.yaml
general:
  domain: -10,35,20,52
  domainName: 'SILEX'
  crs: 3035
  use_sedoo_drive: True 
  root_data: /home/paugamr/data/
hs:
  dir_data: ORIGIN/hotspots/
  sats: ['']
event:
  dir_data: ORIGIN/fire_events 
  dir_geoJson: ORIGIN/fire_events/GeoJson
  dir_frp: ORIGIN/fire_events/FRP
  start_time: '2025-06-28_0000'
  mask_HS: mask_hs_600m_europe.nc
  eurostat: 'EUROSTAT/COMM_RG_01M_2016_3035.gpkg'
  cloudMask_mtg: "FCI/RASTER/cloudMask/"
postproc:
  dir_FWI:  AROME/FWI
  dir_WIND: AROME/FORECAST/WIND/
OLD:  
  #file_HSDensity_ESAWorldCover: /home/paugamr/data/HotspotDensity2024/HSDensity/hs_density_europe.vrt
  #threshold_HSDensity_ESAWorldCover: 11 
  #file_polygonIndus_OSM: /home/paugamr/data/OSM/industrialZone_osmSource-europe.geojson
  #dir_FWI:  /mnt/dataEstrella2/SILEX/AROME/FWI
  #dir_WIND: /mnt/dataEstrella2/SILEX/AROME/FORECAST/WIND/
  #dir_data: /home/paugam/SEDOO/VIIRS/fire_events/ 
  #dir_geoJson: /home/paugam/SEDOO/VIIRS/fire_events/GeoJson/
  #start_time: '2025-06-10_0000'
