# config.yaml
general:
  domain: -10,29,40,45
  domainName: 'MED'
  crs: 3035
  use_sedoo_drive: False 
  root_data: /data/shared/
hs:
  dir_data: ORIGIN/hotspots2025
  sats: ['']
event:
  dir_data: ORIGIN/MED_fire_events 
  dir_geoJson: ORIGIN/MED_fire_events/GeoJson
  dir_frp: ORIGIN/MED_fire_events/FRP
  dir_cloudMask: ORIGIN/RASTER/cloudMask/
  start_time: '2025-01-01_0000'
  mask_HS: mask_hs_600m_med.nc
  eurostat: 'EUROSTAT/COMM_RG_01M_2016_3035.gpkg'
  cloudMask_mtg: "FCI/RASTER/cloudMask/"
postproc:
  dir_FWI:  AROME/FWI
  dir_WIND: AROME/FORECAST/WIND/

